spring:
  jackson:
    serialization: {write-dates-as-timestamps: false}
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2b8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    password: 123456
    max-wait: 30000 # 连接池最大阻塞等待时间（使用负值时表示没有限制）
    max-active: 100 # 连接池的最大连接数（使用负值时表示没有限制）
    max-idle: 20 # 连接池中的最大空闲连接
    min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000 # 连接超时


server:
  port: 8001

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
